### ISSUE TITLE
我很关注图像分类的自监督进展

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PASSL#110]
小弟想问问,对于图像分类的自监督,目前是什么进展呢?比如猫狗分类这种典型的二分类准确率如何?imagenet1k分类准确率如何?PASSL里面的关于图像分类的自监督算法或者模型,有哪些?能给个例子,让我知道如何使用吗?目前看到PASSLissues才1条,文档完全没看到.方便加个微信或者QQ聊几句吗?小弟对于图像分类的自监督高度重视.还有一个疑问,关于图像分类的自监督模型,是不是我给一堆图片,模型运行后,就会把图片归类呢?我需不需要给出类别的数量呢?说白了,我想知道图像分类的自监督的一个使用流程.现在都1.0了,该有点用处了吧.如果一个模型运行后,图像就分好类了,归纳为N类,我有什么办法判断分类的正确性呢?这方面有算法吗?
提了很多问题,跪求每个问题都回答一下,谢谢大佬.

**Comment by yuwoyizhan** [comment]
@firestonelib

**Comment by firestonelib** [comment]
@yuwoyizhan 第1、2个问题：图像分类可以看作视觉自监督预训练模型的一个下游子任务，视觉自监督任务的常见下游任务主要包含图像分类、目标检测、实例分割、语义分割以及姿态估计等。就图像分类而言，基于MIM的自监督模型发展火热并达到SOTA，比如 [BEiT-Large](https://arxiv.org/abs/2106.08254) 在 [ImageNet-1k](https://paperswithcode.com/sota/image-classification-on-imagenet)  上的 top1 acc 为 88.60%，百度自研视觉 MIM 自监督算法 [CAE-Large](https://arxiv.org/pdf/2202.03026.pdf) 在 ImageNet-1k 上的 Finetune 分类 top1 acc 达到 86.29%。
第3、4个问题：PASSL 里面的自监督算法都可以进行下游图像分类任务，比如 Linear Probing。 PASSL 文档在 [PASSL docs](https://github.com/PaddlePaddle/PASSL/tree/main/docs) 中。
使用流程：1.在无标签数据集上进行模型预训练；2.在有标签数据集上进行 Finetune 微调或 Linear Probing 线性评估。
飞桨 PASSL 技术交流群：
![be2ff0e51395bd3d1d84f809ce1f9bc8](https://user-images.githubusercontent.com/9363289/163755129-6ffc7fe8-5cb7-4ef0-979e-cb6fc1623803.jpeg)

**Comment by ChenjieXu** [comment]
> @yuwoyizhan 第1、2个问题：图像分类可以看作视觉自监督预训练模型的一个下游子任务，视觉自监督任务的常见下游任务主要包含图像分类、目标检测、实例分割、语义分割以及姿态估计等。就图像分类而言，基于MIM的自监督模型发展火热并达到SOTA，比如 [BEiT-Large](https://arxiv.org/abs/2106.08254) 在 [ImageNet-1k](https://paperswithcode.com/sota/image-classification-on-imagenet) 上的 top1 acc 为 88.60%，百度自研视觉 MIM 自监督算法 [CAE-Large](https://arxiv.org/pdf/2202.03026.pdf) 在 ImageNet-1k 上的 Finetune 分类 top1 acc 达到 86.29%。 第3、4个问题：PASSL 里面的自监督算法都可以进行下游图像分类任务，比如 Linear Probing。 PASSL 文档在 [PASSL docs](https://github.com/PaddlePaddle/PASSL/tree/main/docs) 中。 使用流程：1.在无标签数据集上进行模型预训练；2.在有标签数据集上进行 Finetune 微调或 Linear Probing 线性评估。 飞桨 PASSL 技术交流群： ![be2ff0e51395bd3d1d84f809ce1f9bc8 =50x50](https://user-images.githubusercontent.com/9363289/163755129-6ffc7fe8-5cb7-4ef0-979e-cb6fc1623803.jpeg)

你好，哪里可以使用CAE-Large算法。
