### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PASSL#112]
1.passl很多文字都是英文的,包括快速使用等文档,希望可以提供中文文档.
2.希望知道图像分类自监督学习的技术研究目前到达什么程度了.比如猫狗这种二分类准确率如何,imagenet准确率如何,使用passl进行图像分类,需要给类别总数量吗?
3.能加个QQ或者微信聊几句吗?有些疑问,拜托了,大佬.
QQ:1226194560
微信:18820785964

**Comment by firestonelib** [comment]
@yuwoyizhan https://github.com/PaddlePaddle/PASSL/issues/110
