### ISSUE TITLE
Unintended behavior in clip_logit_scale

### ISSUE THREAD

**Issue by minogame** [PaddlePaddle/PASSL#125]
https://github.com/PaddlePaddle/PASSL/blob/83c49e6a5ba3444cee7f054122559d7759152764/passl/modeling/backbones/clip.py#L317

check this issue for reference
https://github.com/PaddlePaddle/Paddle/issues/43710

Suggested approach (with non-public API)
```
logit_scale_buffer = self.logit_scale.clip(-4.6, 4.6)
logit_scale_buffer._share_buffer_to(self.logit_scale)
```

**Comment by firestonelib** [comment]
非常感谢您的反馈，代码已合入～～
