### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TingquanGao** [PaddlePaddle/PASSL#175]
这里的参数是class_num：
https://github.com/PaddlePaddle/PASSL/blob/main/passl/models/vision_transformer.py#L260C18-L260C33

这里是num_classes：
https://github.com/PaddlePaddle/PASSL/blob/main/tasks/ssl/mae/main_finetune.py#L421C41-L421C41

**Comment by GuoxiaWang** [comment]
直接提个pr上来吧，我合入

**Comment by TingquanGao** [comment]
好的
