### ISSUE TITLE
AI studio上是否有PASSL下项目实现课程或公开项目

### ISSUE THREAD

**Issue by wamm0909** [PaddlePaddle/PASSL#25]
AI studio上是否有PASSL下项目实现课程或公开项目，如果有，请给个课程链接，谢谢
https://aistudio.baidu.com/aistudio/projectoverview/public/1

**Comment by firestonelib** [comment]
You can try this: https://github.com/PaddlePaddle/PASSL/blob/main/docs/Train_CLIP_model.md 
The link includes a demo which using texts to retrieve images.

**Comment by wamm0909** [comment]
> You can try this: https://github.com/PaddlePaddle/PASSL/blob/main/docs/Train_CLIP_model.md
> The link includes a demo which using texts to retrieve images.

thanks, and i  want to use paddlepaddle/moco v2 (https://github.com/PaddlePaddle/PASSL/blob/main/configs/moco/moco_v2_r50.yaml)to do image similarity matching experiments locally（linux or mac）, can you give me some suggestions

**Comment by firestonelib** [comment]
First of all, you can download paddle moco v2 model from our [MoCo doc](https://github.com/PaddlePaddle/PASSL/blob/main/docs/Train_MoCo_model.md)  ,
Second, you should extract the moco v2 backbone weights following the step 2 in our [MoCo doc](https://github.com/PaddlePaddle/PASSL/blob/main/docs/Train_MoCo_model.md) .
Last but not least, you can run your image similarity matching experiments following our [clip demo](https://github.com/PaddlePaddle/PASSL/blob/main/docs/Train_CLIP_model.md).

**Comment by wamm0909** [comment]
> AI Studio Project: https://aistudio.baidu.com/aistudio/projectdetail/2332016?_=1630569049096

buddy, your update is very timely. I have been using the clip demo just now to encounter'' image_input.npy ''(github), which solved this, but it also prompted ValueError: `paddle.load` can not parse the file:ViT-B-32.pdparams .I am running on a mac.I just want to experiment with moco, it's too torturous

**Comment by wamm0909** [comment]
> > AI Studio Project: https://aistudio.baidu.com/aistudio/projectdetail/2332016?_=1630569049096
> 
> buddy, your update is very timely. I have been using the clip demo just now to encounter'' image_input.npy ''(github), which solved this, but it also prompted ValueError: `paddle.load` can not parse the file:ViT-B-32.pdparams .I am running on a mac.I just want to experiment with moco, it's too torturous

paddle version：2.1.2

**Comment by firestonelib** [comment]
Do you install passl correctively? or download vit-b-32 model? 
Make sure the code bellow is run fluently:
```
pip install passl==0.0.4 -U -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install scikit-image -U -i https://pypi.tuna.tsinghua.edu.cn/simple
wget https://passl.bj.bcebos.com/models/ViT-B-32.pdparams
```
