### ISSUE TITLE
MLP-Mixer: An all-MLP Architecture for Vision

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PASSL#57]
readme文件里的两个模型的TOP1 是不是写反了？模型大的准确度比模型小的准确度小一些？

Arch | Weight | Top-1 Acc | Top-5 Acc | Crop ratio | # Params
-- | -- | -- | -- | -- | --
mlp_mixer_b16_224 | pretrain 1k | 76.60 | 92.23 | 0.875 | 60.0M
mlp_mixer_l16_224 | pretrain 1k | 72.06 | 87.67 | 0.875 | 208.2M

**Comment by firestonelib** [comment]
@lmk123568

**Comment by lmk123568** [comment]
> readme文件里的两个模型的TOP1 是不是写反了？模型大的准确度比模型小的准确度小一些？
> 
> Arch	Weight	Top-1 Acc	Top-5 Acc	Crop ratio	# Params
> mlp_mixer_b16_224	pretrain 1k	76.60	92.23	0.875	60.0M
> mlp_mixer_l16_224	pretrain 1k	72.06	87.67	0.875	208.2M
<img width="437" alt="截屏2021-11-19 17 16 25" src="https://user-images.githubusercontent.com/60082702/142597462-36a57c48-5ff3-460e-8b6f-bd027adce2c8.png">

**Comment by lmk123568** [comment]
> readme文件里的两个模型的TOP1 是不是写反了？模型大的准确度比模型小的准确度小一些？
> 
> Arch	Weight	Top-1 Acc	Top-5 Acc	Crop ratio	# Params
> mlp_mixer_b16_224	pretrain 1k	76.60	92.23	0.875	60.0M
> mlp_mixer_l16_224	pretrain 1k	72.06	87.67	0.875	208.2M

感谢关注PASSL，详细可看[MLP-Mixer](https://arxiv.org/pdf/2105.01601.pdf)
