### ISSUE TITLE
预训练模型key对齐paddle系列backbone

### ISSUE THREAD

**Issue by wanmeiziyoulan** [PaddlePaddle/PASSL#66]
目前自监督系列的预训练模型，如r50，应用到分类、目标检测任务上时，需要把模型key手动对齐paddleclas 的r50才能使用。希望可以有一个通用化的转化脚本，不然更换backbone后还需定制化对齐key，使用起来比较麻烦。
期待尽快可以release通用转化脚本！感谢！

**Comment by lmk123568** [comment]
> 目前自监督系列的预训练模型，如r50，应用到分类、目标检测任务上时，需要把模型key手动对齐paddleclas 的r50才能使用。希望可以有一个通用化的转化脚本，不然更换backbone后还需定制化对齐key，使用起来比较麻烦。 期待尽快可以release通用转化脚本！感谢！

您的反馈非常重要，十分感谢你的反馈，后续我们会做相关的优化工作，敬请期待！
